Componente SideBar
fmteixeira/front-end-stack pull request #9
Opened 2021-04-23 14:48 UTC by Talion1999

## Descrição
Criação do componente SideBar para o projeto de estágio.
Este componente é composto por outros dois:
- SideBarHeader: possui a fotografia do utilizador e o respetivo nome.
- SideBarButtons: possui os botões para navegar na aplicação.

## Contexto
https://www.figma.com/file/M0H6CQoJPQ6yNYy5q5jauC/Chat-Dashboard-(1)?node-id=253%3A1

## Screenshots (se aplicável):
![SideBar](https://user-images.githubusercontent.com/69521585/115888795-d992b780-a442-11eb-9afd-9c4403dc71bd.png)

2021-04-23 15:13 UTC, fmteixeira requested changes

2021-04-23 15:13 UTC, fmteixeira commented on src/Components/SideBar/SideBarHeader/SideBarHeader.tsx
> +
A imagem tem que variar de acordo com o utilizador, mete uma prop nova que é o url da imagem (por ex: "avatarUrl: string"). No ficheiro da história, importas a imagem lá e metes nas props da história.

2021-04-23 15:13 UTC, fmteixeira commented on src/Components/SideBar/SideBarButtons/SideBarButtons.tsx
> +import logout from "../../../resources/media/icons/sidebar/logout.svg";
Transforma isto num componente react com o svg lá dentro e adiciona animação de transição quando está ativo/desativado, igual à dos botões.

2021-04-23 15:13 UTC, fmteixeira commented on src/Components/SideBar/SideBarButtons/SideBarButtons.tsx
> +};
Em vez de guardares uma string e fazeres uma comparação manualmente faz o seguinte:

1. Em vez de repetir manualmente cada botao, faz um componente HeaderButton
2. Renderiza o HeaderButton a partir de um array, como o array é sempre igual podes meter ele em cima fora do componente onde está a interface Props para nao ter que inicializar o array todas as vezes que o componente rederiza
3. O useState apenas guarda o index do ativo atual, inicialmente seria o 1 que é o "Chat" que é o segundo elemento
4. O HeaderButton aceita um index, quando ele é clicado ele envia o seu index
4. O HeaderButton aceita uma prop active que é um boolean para saber se está ativo ou não
5. Adiciona um type ao useState

2021-04-23 22:37 UTC, Talion1999 commented on src/Components/SideBar/SideBarButtons/SideBarButtons.tsx
> +import logout from "../../../resources/media/icons/sidebar/logout.svg";
Quando dizes para transformar isto num componente, estás a dizer para converter os Svgs em Componentes React?

2021-04-23 22:53 UTC, Talion1999 commented on src/Components/SideBar/SideBarButtons/SideBarButtons.tsx
> +import logout from "../../../resources/media/icons/sidebar/logout.svg";
Nevermind, já consegui fazer uma coisa interessante, que é converter as svgs num componente react, pode ser que funcione

2021-04-24 20:28 UTC, fmteixeira requested changes

2021-04-24 20:28 UTC, fmteixeira commented on src/Components/SideBar/SideBarButtons/HeaderButton/SvgIcon/SvgIcon.tsx
> +};
Em vez de ter este array, eu diria para fazeres com que este componente seja dinâmico. Ele aceita um svg como prop e retorna o componente svg.
No componente SideBarButtons crias uma interface para o botao, onde é guardado o texto e o icon. Guardas lá a lista de botoes com esta interface e renderizas os botoes com o icon correspondente.

2021-04-24 20:28 UTC, fmteixeira commented on src/Components/SideBar/SideBarButtons/SideBarButtons.tsx
> +
Os icones estariam guardados aqui.

2021-04-24 20:28 UTC, fmteixeira commented on src/Components/SideBar/SideBarButtons/SideBarButtons.tsx
> +                        />
O icone é passado por aqui e renderizado de acordo.

2021-04-26 20:04 UTC, Talion1999 commented
SideBar Versão Mobile

![SideBar Responsive](https://user-images.githubusercontent.com/69521585/116143410-a5312c80-a6ca-11eb-8354-f2ed050de5bd.png)

2021-05-04 17:31 UTC, fmteixeira requested changes

2021-05-04 17:31 UTC, fmteixeira commented on src/Components/SideBar/SideBarButtons/HeaderButton/SvgIcon/SvgIcon.tsx
> +};
Quem utiliza este componente não sabe que tipo de valores ele pode introduzir sem ser lendo o código.
Em vez de passar o url, cria um enumerado e é só passar um dos valores do enumerado para renderizar o componente pretendido.
Podes criar também uma função que tem um switch, que dependendo do enumerado selecionado, renderiza o icon correto.

2021-05-04 17:36 UTC, fmteixeira commented on src/Components/SideBar/SideBarButtons/HeaderButton/SvgIcon/SvgIcon.tsx
> +};
Aplica a mesma lógica ao HeaderButton, o HeaderButton tem um enumerado de buttons que renderiza e o svgicon tem um igual.

2021-05-05 14:24 UTC, fmteixeira approved these changes

2021-05-05 14:27 UTC, fmteixeira requested changes
Não consigo clicar na area da direita para selecionar, o botao deve ter a largura toda:
![image](https://user-images.githubusercontent.com/32296976/117156902-aab70280-adad-11eb-99e4-70314ae39683.png)

2021-05-05 20:34 UTC, fmteixeira approved these changes

2021-05-05 20:35 UTC, merged